project:
  type: website

website:
  title: "My Blog"
  site-url: https://www.jonathankierce.com
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts

format:
  html:
    theme: cosmo
    css: styles.css
