project:
  type: website

website:
  title: "My Blog"
  site-url: https://jonathankierce.com
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts

format:
  html:
    theme: cosmo
    css: styles.css
    grid:
      body-width: 1200px
      margin-width: 180px
